name : Test cpx
on: push
jobs:
  cpx:
    runs-on: ubuntu-latest

    steps:
      - name: Install cpx
        run: curl -sL https://git.io/cpm | sudo perl - install -g App::cpx@0.03
      - name: cpx hr 
        run: cpx hr -s 40
